server:
  port: 8762

spring:
  application:
    name: zuul-server

#management:
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#  endpoint:
#    health:
#      show-details: "ALWAYS"
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
#    pause:
#      enabled: true
#    restart:
#      enabled: true
#    resume:
#      enabled: true
#    shutdown:
#      enabled: true
#
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#        exclude: env

eureka:
  instance:
    appname: zuul-server
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /api
  routes:
    emailService:
      path: /email/**
      serviceId: emailService
    pushService:
      path: /push/**
      serviceId: pushService
    smsService:
      path: /sms/**
      serviceId: smsService
