server:
  port: 9003

spring:
  application:
    name: pushService

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka