server:
  port: 9001

spring:
  application:
    name: emailService
  mail:
    host: smtp.gmail.com
    port: 587
    username: testrafaret@gmail.com
    password: qw12er34ty56
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka